name: Schedule Workflow

on:
  schedule:
    - cron: '/5 * * * *'

jobs:
  ingest_opsgenie_data_to_port_job:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools
          pip install --no-cache-dir -r requirements.txt
      - name: Run Script
        env:
          PORT_CLIENT_ID: ${{ secrets.PORT_CLIENT_ID }}
          PORT_CLIENT_SECRET: ${{ secrets.PORT_CLIENT_SECRET }}
          OPSGENIE_API_KEY: ${{ secrets.OPSGENIE_API_KEY }}
        run: |
          echo "Getting OpsGenie on-call users"
          python opsgenie/app.py
    if: github.event_name == 'schedule'
